version: '3.8'
services:
  order-service:
    image: com.food.ordering.system/order.service:1.0-SNAPSHOT
    container_name: order-service
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_container:5432/postgres?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
      KAFKA-CONFIG_BOOTSTRAP-SERVERS: "local-confluent-kafka-cp-kafka-headless:9092"
      KAFKA-CONFIG_SCHEMA-REGISTRY-URL: "http://local-confluent-kafka-cp-schema-registry:8081"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1024M"
        reservations:
          cpus: "0.2"
          memory: "256M"

  payment-service:
    image: com.food.ordering.system/payment.service:1.0-SNAPSHOT
    container_name: payment-service
    ports:
      - "8182:8182"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_container:5432/postgres?currentSchema=payment&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
      KAFKA-CONFIG_BOOTSTRAP-SERVERS: "local-confluent-kafka-cp-kafka-headless:9092"
      KAFKA-CONFIG_SCHEMA-REGISTRY-URL: "http://local-confluent-kafka-cp-schema-registry:8081"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1024M"
        reservations:
          cpus: "0.2"
          memory: "256M"

  restaurant-service:
    image: com.food.ordering.system/restaurant.service:1.0-SNAPSHOT
    container_name: restaurant-service
    ports:
      - "8183:8183"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_container:5432/postgres?currentSchema=restaurant&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
      KAFKA-CONFIG_BOOTSTRAP-SERVERS: "local-confluent-kafka-cp-kafka-headless:9092"
      KAFKA-CONFIG_SCHEMA-REGISTRY-URL: "http://local-confluent-kafka-cp-schema-registry:8081"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1024M"
        reservations:
          cpus: "0.2"
          memory: "256M"

  customer-service:
    image: com.food.ordering.system/customer.service:1.0-SNAPSHOT
    container_name: customer-service
    ports:
      - "8184:8184"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_container:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
      KAFKA-CONFIG_BOOTSTRAP-SERVERS: "local-confluent-kafka-cp-kafka-headless:9092"
      KAFKA-CONFIG_SCHEMA-REGISTRY-URL: "http://local-confluent-kafka-cp-schema-registry:8081"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1024M"
        reservations:
          cpus: "0.2"
          memory: "256M"
